# Generated by Django 4.0.4 on 2022-05-11 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commentsAndReplies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=255)),
                ('album_id', models.IntegerField(unique=True)),
                ('track_id', models.IntegerField(unique=True)),
                ('album_title', models.CharField(max_length=255)),
                ('track_title', models.CharField(max_length=255)),
                ('artist_name', models.CharField(max_length=255)),
                ('album_image', models.CharField(max_length=255)),
                ('preview_track', models.CharField(max_length=255)),
                ('comments', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='commentsAndReplies.comments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
