# Generated by Django 4.0.4 on 2022-05-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='album_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='track_id',
            field=models.IntegerField(),
        ),
    ]
