# Generated by Django 4.0.4 on 2022-05-19 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_comment_post_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='track_id',
            field=models.IntegerField(blank=True),
        ),
    ]
