# Generated by Django 4.0.4 on 2022-05-04 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friends', '0002_friendlist_remove_friendrequest_dateandtime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendshipStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAndTime', models.DateTimeField(auto_now=True)),
                ('requestTo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requestTo_status', to=settings.AUTH_USER_MODEL)),
                ('requestor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requestor_status', to=settings.AUTH_USER_MODEL)),
                ('specifier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StatusCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('R', 'requested'), ('A', 'accepted'), ('D', 'declined'), ('B', 'blocked')], default='R', max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='dateAndTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='requestTo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requestTo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='requestor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requestor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='FriendList',
        ),
        migrations.AddField(
            model_name='friendshipstatus',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='friends.statuscode'),
        ),
    ]
