# Generated by Django 4.0.4 on 2022-05-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_friendshipstatus_statuscode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendshipstatus',
            name='specifier',
        ),
        migrations.AlterField(
            model_name='friendshipstatus',
            name='status',
            field=models.CharField(choices=[('R', 'requested'), ('A', 'accepted'), ('D', 'declined')], default='R', max_length=1),
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
        migrations.DeleteModel(
            name='StatusCode',
        ),
    ]
