# Generated by Django 4.0.4 on 2022-05-04 21:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friends', '0004_remove_friendshipstatus_specifier_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendshipstatus',
            unique_together={('requestor', 'requestTo')},
        ),
    ]
