# Generated by Django 4.0.4 on 2022-05-05 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0005_alter_friendshipstatus_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendshipstatus',
            name='status',
            field=models.CharField(choices=[('Requested', 'requested'), ('Accepted', 'accepted'), ('Declined', 'declined')], default='Requested', max_length=9),
        ),
    ]
